# Generated by Django 6.0.3 on 2026-04-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_song_prompt_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='prompt_mode',
            field=models.CharField(choices=[('idea', 'Idea'), ('lyric', 'Lyric')], default='lyric', max_length=10),
        ),
    ]
