# Generated by Django 6.0.3 on 2026-04-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_alter_song_prompt_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
